/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Academic.Enrollment;
import Business.Business;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Yiru Chen
 */
public class StudentWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    StudentProfile student;
    private UserAccount studentAccount;

    /**
     * Creates new form UnitRiskWorkArea
     * @param b
     * @param spp
     * @param clp
     */

    public StudentWorkAreaJPanel(Business b, StudentProfile spp, JPanel clp) {
        this(b, spp, clp, null);
    }

    public StudentWorkAreaJPanel(Business b, StudentProfile spp, JPanel clp, UserAccount account) {
        business = b;
        this.CardSequencePanel = clp;
        student = spp;
        studentAccount = account;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCoursework = new javax.swing.JButton();
        btnGraduation = new javax.swing.JButton();
        btnRegistration = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTranscript = new javax.swing.JButton();
        btnPorfile = new javax.swing.JButton();

        setForeground(new java.awt.Color(51, 51, 51));

        btnCoursework.setBackground(new java.awt.Color(102, 153, 255));
        btnCoursework.setFont(getFont());
        btnCoursework.setForeground(new java.awt.Color(255, 255, 255));
        btnCoursework.setText("Coursework Management");
        btnCoursework.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCoursework.setMaximumSize(new java.awt.Dimension(200, 40));
        btnCoursework.setMinimumSize(new java.awt.Dimension(20, 23));
        btnCoursework.setPreferredSize(new java.awt.Dimension(240, 30));
        btnCoursework.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseworkIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnGraduation.setBackground(new java.awt.Color(102, 153, 255));
        btnGraduation.setFont(getFont());
        btnGraduation.setForeground(new java.awt.Color(255, 255, 255));
        btnGraduation.setText("Graduation Audit");
        btnGraduation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGraduation.setMaximumSize(new java.awt.Dimension(200, 40));
        btnGraduation.setMinimumSize(new java.awt.Dimension(20, 20));
        btnGraduation.setPreferredSize(new java.awt.Dimension(240, 25));
        btnGraduation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraduationActionPerformed(evt);
            }
        });

        btnRegistration.setBackground(new java.awt.Color(102, 153, 255));
        btnRegistration.setFont(getFont());
        btnRegistration.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistration.setText("Registration");
        btnRegistration.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistration.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRegistration.setMinimumSize(new java.awt.Dimension(20, 20));
        btnRegistration.setPreferredSize(new java.awt.Dimension(240, 25));
        btnRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrationActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("My Student Portal");

        btnTranscript.setBackground(new java.awt.Color(102, 153, 255));
        btnTranscript.setFont(getFont());
        btnTranscript.setForeground(new java.awt.Color(255, 255, 255));
        btnTranscript.setText("Transcript");
        btnTranscript.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTranscript.setMaximumSize(new java.awt.Dimension(200, 40));
        btnTranscript.setMinimumSize(new java.awt.Dimension(20, 20));
        btnTranscript.setPreferredSize(new java.awt.Dimension(240, 25));
        btnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscriptActionPerformed(evt);
            }
        });

        btnPorfile.setBackground(new java.awt.Color(102, 153, 255));
        btnPorfile.setFont(getFont());
        btnPorfile.setForeground(new java.awt.Color(255, 255, 255));
        btnPorfile.setText("My Profile");
        btnPorfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPorfile.setMaximumSize(new java.awt.Dimension(200, 40));
        btnPorfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnPorfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnPorfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnGraduation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(btnCoursework, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(btnPorfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTranscript, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(btnRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap(548, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCoursework, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGraduation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTranscript, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btnPorfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseworkIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseworkIdentifyResourceAssetsActionPerformed
        String studentId = getStudentId();
if (studentId == null) {
    JOptionPane.showMessageDialog(this,
            "Student session is invalid.",
            "Error",
            JOptionPane.ERROR_MESSAGE);
    return;
}

String courseId = promptRequired("Enter course ID for assignment submission:");
if (courseId == null) {
    return;
}

String assignmentName = promptRequired("Enter assignment name:");
if (assignmentName == null) {
    return;
}


boolean saved = business.getEnrollmentDirectory().submitAssignment(studentId, courseId, assignmentName);

if (!saved) {
    JOptionPane.showMessageDialog(this,"Submission failed. Enroll in the course before submitting coursework.","Validation Error",JOptionPane.WARNING_MESSAGE);
    return;
}


    ArrayList<String> submissions = business.getEnrollmentDirectory()
        .getSubmittedAssignments(studentId);

        StringBuilder sb = new StringBuilder("Submission accepted.\n\nCurrent submissions:\n");
    for (String line : submissions) {
    sb.append(" - ").append(line).append("\n");
}

JOptionPane.showMessageDialog(this,sb.toString(),"Coursework",JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnCourseworkIdentifyResourceAssetsActionPerformed

    private void btnGraduationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraduationActionPerformed
        String studentId = getStudentId();
        if (studentId == null) {
            JOptionPane.showMessageDialog(this, "Student session invalid.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
         int completed = business.getEnrollmentDirectory().completedCredits(studentId);
        int graduationRequiredCredits = 30;
        int pending = Math.max(0, graduationRequiredCredits - completed);
        String status = pending == 0 ? "Eligible for graduation" : "Credits pending: " + pending;
        JOptionPane.showMessageDialog(this,
                "Graduation Audit\nCompleted Credits: " + completed + "\nRequired Credits: "
                        + graduationRequiredCredits + "\nStatus: " + status,
                "Graduation Audit", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_btnGraduationActionPerformed

    private void btnRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrationActionPerformed
        String studentId = getStudentId();
        if (studentId == null) {
            JOptionPane.showMessageDialog(this, "Student session invalid.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String action = JOptionPane.showInputDialog(this,
                "Type action: ENROLL or DROP");
        if (action == null || action.trim().isEmpty()) {
            return;
        }

        if ("ENROLL".equalsIgnoreCase(action.trim())) {
            String courseId = promptRequired("Enter course ID:");
            if (courseId == null) {
                return;
            }
            String courseName = promptRequired("Enter course name:");
            if (courseName == null) {
                return;
            }
            String creditsText = promptRequired("Enter credits:");
            if (creditsText == null) {
                return;
            }
            try {
                int credits = Integer.parseInt(creditsText);
                business.getEnrollmentDirectory().registerStudentForCourse(studentId, courseId, courseName, credits);
                JOptionPane.showMessageDialog(this, "Enrollment successful.", "Registration",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Credits must be an integer.", "Validation Error",
                        JOptionPane.WARNING_MESSAGE);
            }
            return;
        }

        if ("DROP".equalsIgnoreCase(action.trim())) {
            String courseId = promptRequired("Enter course ID to drop:");
            if (courseId == null) {
                return;
            }
            boolean removed = business.getEnrollmentDirectory().dropStudentCourse(studentId, courseId);
            JOptionPane.showMessageDialog(this,
                    removed ? "Course dropped successfully." : "Course not found in enrollment.",
                    "Registration", removed ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.WARNING_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(this, "Unknown action. Use ENROLL or DROP.", "Validation Error",
                JOptionPane.WARNING_MESSAGE);
}//GEN-LAST:event_btnRegistrationActionPerformed

    private void btnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscriptActionPerformed
        String studentId = getStudentId();
        if (studentId == null) {
            JOptionPane.showMessageDialog(this, "Student session invalid.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        StringBuilder transcript = new StringBuilder("Transcript\n\n");
        ArrayList<String> lines =business.getEnrollmentDirectory().transcriptLines(studentId);

    for (String line : lines) {
        transcript.append(line).append("\n");
        
        }
       ArrayList<Enrollment> current =business.getEnrollmentDirectory().getEnrollmentsForStudent(studentId);
        transcript.append("\nCurrent course count: ").append(current.size());
        JOptionPane.showMessageDialog(this, transcript.toString(), "Transcript", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTranscriptActionPerformed

    private void btnPorfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPorfileActionPerformed

    private String promptRequired(String message) {
        String value = JOptionPane.showInputDialog(this, message);
        if (value == null || value.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Input is required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        return value.trim();
    }

    private String getStudentId() {
        if (student == null || student.getPerson() == null) {
            return null;
        }
        return student.getPerson().getPersonId();
    }

    private String safe(String value) {
        return value == null ? "" : value;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCoursework;
    private javax.swing.JButton btnGraduation;
    private javax.swing.JButton btnPorfile;
    private javax.swing.JButton btnRegistration;
    private javax.swing.JButton btnTranscript;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
