/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.WorkAreas.StudentRole;


import Business.Academic.Enrollment;
import Business.Business;
import Business.Person.Person;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class StudentWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    StudentProfile student;
    private UserAccount studentAccount;

    /**
     * Creates new form UnitRiskWorkArea
     * @param b
     * @param spp
     * @param clp
     */

    public StudentWorkAreaJPanel(Business b, StudentProfile spp, JPanel clp) {
        this(b, spp, clp, null);
    }

    public StudentWorkAreaJPanel(Business b, StudentProfile spp, JPanel clp, UserAccount account) {
        business = b;
        this.CardSequencePanel = clp;
        student = spp;
        studentAccount = account;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();

        setForeground(new java.awt.Color(51, 51, 51));

        jButton4.setBackground(new java.awt.Color(102, 153, 255));
        jButton4.setFont(getFont());
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Course Work");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setMaximumSize(new java.awt.Dimension(200, 40));
        jButton4.setMinimumSize(new java.awt.Dimension(20, 23));
        jButton4.setPreferredSize(new java.awt.Dimension(240, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4IdentifyResourceAssetsActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(102, 153, 255));
        jButton9.setFont(getFont());
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Manage Profile");
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.setMaximumSize(new java.awt.Dimension(200, 40));
        jButton9.setMinimumSize(new java.awt.Dimension(20, 20));
        jButton9.setPreferredSize(new java.awt.Dimension(240, 25));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(102, 153, 255));
        jButton10.setFont(getFont());
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Graduation Audit");
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.setMaximumSize(new java.awt.Dimension(200, 40));
        jButton10.setMinimumSize(new java.awt.Dimension(20, 20));
        jButton10.setPreferredSize(new java.awt.Dimension(240, 25));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(102, 153, 255));
        jButton11.setFont(getFont());
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Registration");
        jButton11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.setMaximumSize(new java.awt.Dimension(200, 40));
        jButton11.setMinimumSize(new java.awt.Dimension(20, 20));
        jButton11.setPreferredSize(new java.awt.Dimension(240, 25));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("My Student Portal");

        jButton12.setBackground(new java.awt.Color(102, 153, 255));
        jButton12.setFont(getFont());
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Transcript");
        jButton12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.setMaximumSize(new java.awt.Dimension(200, 40));
        jButton12.setMinimumSize(new java.awt.Dimension(20, 20));
        jButton12.setPreferredSize(new java.awt.Dimension(240, 25));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(590, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4IdentifyResourceAssetsActionPerformed
        String studentId = getStudentId();
if (studentId == null) {
    JOptionPane.showMessageDialog(this,
            "Student session is invalid.",
            "Error",
            JOptionPane.ERROR_MESSAGE);
    return;
}

String courseId = promptRequired("Enter course ID for assignment submission:");
if (courseId == null) {
    return;
}

String assignmentName = promptRequired("Enter assignment name:");
if (assignmentName == null) {
    return;
}


boolean saved = business.getEnrollmentDirectory().submitAssignment(studentId, courseId, assignmentName);

if (!saved) {
    JOptionPane.showMessageDialog(this,"Submission failed. Enroll in the course before submitting coursework.","Validation Error",JOptionPane.WARNING_MESSAGE);
    return;
}


    ArrayList<String> submissions = business.getEnrollmentDirectory()
        .getSubmittedAssignments(studentId);

        StringBuilder sb = new StringBuilder("Submission accepted.\n\nCurrent submissions:\n");
    for (String line : submissions) {
    sb.append(" - ").append(line).append("\n");
}

JOptionPane.showMessageDialog(this,sb.toString(),"Coursework",JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jButton4IdentifyResourceAssetsActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (student == null || student.getPerson() == null) {
            JOptionPane.showMessageDialog(this, "Student profile missing.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Person p = student.getPerson();
        String summary = "Name: " + safe(p.getName()) + "\nEmail: " + safe(p.getEmail()) + "\nDepartment: "
                + safe(p.getDepartment()) + "\nHobbies: " + safe(student.getHobbies()) + "\nInterests: "
                + safe(student.getInterests()) + "\nAcademic Progress: " + safe(student.getAcademicProgress());
        JOptionPane.showMessageDialog(this, summary, "Manage Profile", JOptionPane.INFORMATION_MESSAGE);

        String newHobbies = JOptionPane.showInputDialog(this, "Update hobbies:", safe(student.getHobbies()));
        if (newHobbies == null) {
            return;
        }
        String newInterests = JOptionPane.showInputDialog(this, "Update interests:", safe(student.getInterests()));
        if (newInterests == null) {
            return;
        }
        String newProgress = JOptionPane.showInputDialog(this, "Update academic progress:",
                safe(student.getAcademicProgress()));
        if (newProgress == null || newProgress.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Academic progress cannot be empty.", "Validation Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        student.setHobbies(newHobbies.trim());
        student.setInterests(newInterests.trim());
        student.setAcademicProgress(newProgress.trim());
        if (studentAccount != null) {
            studentAccount.touchLastUpdated();
        }
        JOptionPane.showMessageDialog(this, "Student profile updated.", "Success", JOptionPane.INFORMATION_MESSAGE);


}//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String studentId = getStudentId();
        if (studentId == null) {
            JOptionPane.showMessageDialog(this, "Student session invalid.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
         int completed = business.getEnrollmentDirectory().completedCredits(studentId);
        int graduationRequiredCredits = 30;
        int pending = Math.max(0, graduationRequiredCredits - completed);
        String status = pending == 0 ? "Eligible for graduation" : "Credits pending: " + pending;
        JOptionPane.showMessageDialog(this,
                "Graduation Audit\nCompleted Credits: " + completed + "\nRequired Credits: "
                        + graduationRequiredCredits + "\nStatus: " + status,
                "Graduation Audit", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String studentId = getStudentId();
        if (studentId == null) {
            JOptionPane.showMessageDialog(this, "Student session invalid.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String action = JOptionPane.showInputDialog(this,
                "Type action: ENROLL or DROP");
        if (action == null || action.trim().isEmpty()) {
            return;
        }

        if ("ENROLL".equalsIgnoreCase(action.trim())) {
            String courseId = promptRequired("Enter course ID:");
            if (courseId == null) {
                return;
            }
            String courseName = promptRequired("Enter course name:");
            if (courseName == null) {
                return;
            }
            String creditsText = promptRequired("Enter credits:");
            if (creditsText == null) {
                return;
            }
            try {
                int credits = Integer.parseInt(creditsText);
                business.getEnrollmentDirectory().registerStudentForCourse(studentId, courseId, courseName, credits);
                JOptionPane.showMessageDialog(this, "Enrollment successful.", "Registration",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Credits must be an integer.", "Validation Error",
                        JOptionPane.WARNING_MESSAGE);
            }
            return;
        }

        if ("DROP".equalsIgnoreCase(action.trim())) {
            String courseId = promptRequired("Enter course ID to drop:");
            if (courseId == null) {
                return;
            }
            boolean removed = business.getEnrollmentDirectory().dropStudentCourse(studentId, courseId);
            JOptionPane.showMessageDialog(this,
                    removed ? "Course dropped successfully." : "Course not found in enrollment.",
                    "Registration", removed ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.WARNING_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(this, "Unknown action. Use ENROLL or DROP.", "Validation Error",
                JOptionPane.WARNING_MESSAGE);
}//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        String studentId = getStudentId();
        if (studentId == null) {
            JOptionPane.showMessageDialog(this, "Student session invalid.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        StringBuilder transcript = new StringBuilder("Transcript\n\n");
        ArrayList<String> lines =business.getEnrollmentDirectory().transcriptLines(studentId);

    for (String line : lines) {
        transcript.append(line).append("\n");
        
        }
       ArrayList<Enrollment> current =business.getEnrollmentDirectory().getEnrollmentsForStudent(studentId);
        transcript.append("\nCurrent course count: ").append(current.size());
        JOptionPane.showMessageDialog(this, transcript.toString(), "Transcript", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton12ActionPerformed

    private String promptRequired(String message) {
        String value = JOptionPane.showInputDialog(this, message);
        if (value == null || value.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Input is required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        return value.trim();
    }

    private String getStudentId() {
        if (student == null || student.getPerson() == null) {
            return null;
        }
        return student.getPerson().getPersonId();
    }

    private String safe(String value) {
        return value == null ? "" : value;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
