/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Business;
import Business.Person.Person;
import Business.Profiles.FacultyProfile;
import Business.Profiles.Profile;
import Business.UserAccounts.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Jianting Dong
 */
public class AdminFaculty extends javax.swing.JPanel {
  private JPanel userProcessContainer;
    private Business business;
    private ManageFaculty managePanel;
    private FacultyProfile facultyProfile;
    private UserAccount userAccount;
    private ManageFaculty parentPanel;
    /**
     * Creates new form AdminFaculty
     */
 
 
public AdminFaculty(UserAccount ua, Business b, JPanel upc, ManageFaculty parent) {
    initComponents();
    this.userAccount = ua;
    this.business = b;
    this.userProcessContainer = upc;
    this.parentPanel = parent;
    populateFields();
    

        
txtFacultyID.setText(userAccount.getPersonId());
txtUserName.setText(userAccount.getUserLoginName());
txtRole.setText(userAccount.getRole());
    }
    /**
     * Creates new form AdminFaculty
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblRole = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        lblFacultyID = new javax.swing.JLabel();
        lblLastActivity = new javax.swing.JLabel();
        txtFacultyID = new javax.swing.JTextField();
        txtLastActivity = new javax.swing.JTextField();
        lblLastUpdated = new javax.swing.JLabel();
        txtLastUpdated = new javax.swing.JTextField();
        lblNewPassword = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Administer Faculty Account");

        lblName.setText("Name");

        lblEmail.setText("Email");

        jLabel2.setText("Department");

        lblUserName.setText("User Name");

        lblRole.setText("Role");

        lblFacultyID.setText("Faculty ID");

        lblLastActivity.setText("Last Activity");

        lblLastUpdated.setText("Last Updated");

        txtLastUpdated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastUpdatedActionPerformed(evt);
            }
        });

        lblNewPassword.setText("New Password");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update>>");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblEmail)
                            .addComponent(jLabel2)
                            .addComponent(lblUserName)
                            .addComponent(lblRole)
                            .addComponent(lblFacultyID)
                            .addComponent(lblLastActivity)
                            .addComponent(lblLastUpdated)
                            .addComponent(lblNewPassword))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDepartment, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserName)
                            .addComponent(txtRole)
                            .addComponent(txtFacultyID)
                            .addComponent(txtLastActivity)
                            .addComponent(txtLastUpdated)
                            .addComponent(txtNewPassword))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRole)
                    .addComponent(txtRole))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacultyID)
                    .addComponent(txtFacultyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastActivity)
                    .addComponent(txtLastActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastUpdated)
                    .addComponent(txtLastUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPassword)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate))
                .addGap(91, 91, 91))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
 if (parentPanel != null) {
        parentPanel.populateTable();
    }

    userProcessContainer.remove(this);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.previous(userProcessContainer);
    
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
   int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this faculty account?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    Profile profile = userAccount.getAssociatedPersonProfile();

    if (profile instanceof FacultyProfile) {
        FacultyProfile fp = (FacultyProfile) profile;
        business.getFacultyDirectory().removeFacultyProfile(fp);
    }

    business.getUserAccountDirectory().getUserAccountList().remove(userAccount);

    JOptionPane.showMessageDialog(this,
            "Faculty account deleted successfully.",
            "Deleted",
            JOptionPane.INFORMATION_MESSAGE);

    if (parentPanel != null) {
        parentPanel.populateTable();
    }

    userProcessContainer.remove(this);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtLastUpdatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastUpdatedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastUpdatedActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
 if (userAccount == null) {
        JOptionPane.showMessageDialog(this,"No faculty account selected.","Error",JOptionPane.ERROR_MESSAGE);
        return;
    }

    Profile profile = userAccount.getAssociatedPersonProfile();
    Person p = (profile == null) ? null : profile.getPerson();

    if (p == null) {
        JOptionPane.showMessageDialog(this,"Faculty person record not found.","Error",JOptionPane.ERROR_MESSAGE);
        return;
    }

    String name = txtName.getText().trim();
    String email = txtEmail.getText().trim();
    String dept = txtDepartment.getText().trim();
    String newPw = txtNewPassword.getText().trim();

    if (name.isEmpty()) {
        JOptionPane.showMessageDialog(this,"Name is required.","Warning",JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (email.isEmpty()) {
        JOptionPane.showMessageDialog(this,"Email is required.","Warning",JOptionPane.WARNING_MESSAGE);
        return;
    }

    p.setName(name);
    p.setEmail(email);
    p.setDepartment(dept);

    if (!newPw.isEmpty()) {
        userAccount.setPassword(newPw); 
        txtNewPassword.setText("");
    } else {
        userAccount.touchLastUpdated();
    }

    populateFields();

    JOptionPane.showMessageDialog(this,"Updated successfully.","Success",JOptionPane.INFORMATION_MESSAGE);

    if (parentPanel != null) {
        parentPanel.populateTable();
    }


    userProcessContainer.remove(this);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.previous(userProcessContainer);
        }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFacultyID;
    private javax.swing.JLabel lblLastActivity;
    private javax.swing.JLabel lblLastUpdated;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFacultyID;
    private javax.swing.JTextField txtLastActivity;
    private javax.swing.JTextField txtLastUpdated;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNewPassword;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void populateFields() {
        Person p = null;
    if (userAccount != null && userAccount.getAssociatedPersonProfile() != null) {
        p = userAccount.getAssociatedPersonProfile().getPerson();
    }

    if (p != null) {
        txtName.setText(p.getName() == null ? "" : p.getName());
        txtEmail.setText(p.getEmail() == null ? "" : p.getEmail());
        txtDepartment.setText(p.getDepartment() == null ? "" : p.getDepartment());
        txtFacultyID.setText(p.getPersonId() == null ? "" : p.getPersonId());
    } else {
        txtName.setText("");
        txtEmail.setText("");
        txtDepartment.setText("");
        txtFacultyID.setText("");
    }

    if (userAccount != null) {
        txtUserName.setText(userAccount.getUserLoginName());
        txtRole.setText(userAccount.getRole());
        txtLastActivity.setText(userAccount.getLastAccessTime() == null ? "" : userAccount.getLastAccessTime().toString());
        txtLastUpdated.setText(userAccount.getLastUpdatedTime() == null ? "" : userAccount.getLastUpdatedTime().toString());
    } else {
        txtUserName.setText("");
        txtRole.setText("");
        txtLastActivity.setText("");
        txtLastUpdated.setText("");
    }


    txtUserName.setEnabled(false);
    txtRole.setEnabled(false);
    txtFacultyID.setEnabled(false);
    txtLastActivity.setEnabled(false);
    txtLastUpdated.setEnabled(false);
    }

  
    }

