/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;
import Business.Business;
import Business.Person.Person;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Jianting Dong
 */
public class AdminStudents extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Business business;
    private ManageStudents managePanel;
    private StudentProfile studentProfile;
    private UserAccount userAccount;
    
    /**
     * Creates new form AdminStudents
     */
    public AdminStudents(StudentProfile sp, UserAccount ua, Business business,JPanel userProcessContainer, ManageStudents mp) {
    initComponents();
    this.userProcessContainer = userProcessContainer;
    this.business = business;
    this.managePanel = mp;
    this.studentProfile = sp;
    this.userAccount = ua;

    populateFields();
    setViewMode(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblDepartment = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        lblNUID = new javax.swing.JLabel();
        txtNUID = new javax.swing.JTextField();
        lblLastActivity = new javax.swing.JLabel();
        txtLastActivity = new javax.swing.JTextField();
        lblLastUpdated = new javax.swing.JLabel();
        txtLastUpdated = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblNewPassword = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Administer Student Account");

        lblName.setText("Name");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblEmail.setText("Email");

        lblDepartment.setText("Department");

        lblUserName.setText("User Name");

        jLabel2.setText("Role");

        lblNUID.setText("NUID");

        lblLastActivity.setText("Last Activity");

        lblLastUpdated.setText("Last Updated");

        txtLastUpdated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastUpdatedActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update>>");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblNewPassword.setText("New Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLastActivity)
                                    .addComponent(lblLastUpdated)
                                    .addComponent(lblNUID)
                                    .addComponent(jLabel2)
                                    .addComponent(lblUserName)
                                    .addComponent(lblDepartment)
                                    .addComponent(lblEmail)
                                    .addComponent(lblName)
                                    .addComponent(lblNewPassword))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLastUpdated, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNUID, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(txtRole)
                                        .addComponent(txtUserName)
                                        .addComponent(txtDepartment)
                                        .addComponent(txtEmail)
                                        .addComponent(txtName)
                                        .addComponent(txtLastActivity))
                                    .addComponent(btnDelete)
                                    .addComponent(txtNewPassword)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepartment))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserName))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNUID)
                    .addComponent(txtNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLastActivity)
                    .addComponent(txtLastActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastUpdated)
                    .addComponent(txtLastUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblNewPassword))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate))
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastUpdatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastUpdatedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastUpdatedActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    int confirm = JOptionPane.showConfirmDialog(this,"Are you sure you want to delete this student account?","Confirm Delete",JOptionPane.YES_NO_OPTION);

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    if (userAccount != null) {
        business.getUserAccountDirectory().removeUserAccount(userAccount);

    if (userAccount.getAssociatedPersonProfile() instanceof StudentProfile) {
            StudentProfile sp = (StudentProfile) userAccount.getAssociatedPersonProfile();
            business.getStudentDirectory().removeStudentProfile(sp); 
        } else {
            StudentProfile sp = business.getStudentDirectory().findStudent(userAccount.getPersonId());
    if (sp != null) {
                business.getStudentDirectory().removeStudentProfile(sp);
            }
        }
    }

    JOptionPane.showMessageDialog(this, "Student account deleted.");
    btnBackActionPerformed(evt);
        
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
String name = txtName.getText().trim();
    String email = txtEmail.getText().trim();
    String dept = txtDepartment.getText().trim();
    String newPassword = txtNewPassword.getText().trim();

    if (name.isEmpty() || email.isEmpty() || dept.isEmpty()) {
        JOptionPane.showMessageDialog(this,"Please fill Name, Email and Department.","Warning",JOptionPane.WARNING_MESSAGE);
        return;
    }

    Person p = null;
    if (studentProfile != null) {
        p = studentProfile.getPerson();
    }
    if (p == null && userAccount != null) {
        p = userAccount.getAssociatedPersonProfile().getPerson();
    }

    if (p != null) {
        p.setName(name);
        p.setEmail(email);
        p.setDepartment(dept);
    }


    if (!newPassword.isEmpty()) {
        userAccount.setPassword(newPassword); 
        txtNewPassword.setText("");          
    } else {
  
        userAccount.touchLastUpdated();
    }


    txtLastUpdated.setText(
            userAccount.getLastUpdatedTime() == null
                    ? ""
                    : userAccount.getLastUpdatedTime().toString()
    );

    JOptionPane.showMessageDialog(this, "Student account updated successfully.");





    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    userProcessContainer.remove(this);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.previous(userProcessContainer);

    if (managePanel != null) {
            managePanel.populateTable();
        }    }//GEN-LAST:event_btnBackActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
      
    }//GEN-LAST:event_txtNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLastActivity;
    private javax.swing.JLabel lblLastUpdated;
    private javax.swing.JLabel lblNUID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLastActivity;
    private javax.swing.JTextField txtLastUpdated;
    private javax.swing.JTextField txtNUID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNewPassword;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void populateFields() {
        Person p = null;
        if (studentProfile != null && studentProfile.getPerson() != null) {
            p = studentProfile.getPerson();
        } else if (userAccount != null && userAccount.getAssociatedPersonProfile() != null) {
            p = userAccount.getAssociatedPersonProfile().getPerson();
        }

        if (p != null) {
            txtName.setText(p.getName() == null ? "" : p.getName());
            txtEmail.setText(p.getEmail() == null ? "" : p.getEmail());
            txtDepartment.setText(p.getDepartment() == null ? "" : p.getDepartment());
            txtNUID.setText(p.getPersonId() == null ? "" : p.getPersonId());
        } else {
            txtName.setText("");
            txtEmail.setText("");
            txtDepartment.setText("");
            txtNUID.setText(userAccount == null ? "" : userAccount.getPersonId());
        }

  
        if (userAccount != null) {
            txtUserName.setText(userAccount.getUserLoginName());
            txtRole.setText(userAccount.getRole());

            txtLastActivity.setText(userAccount.getLastAccessTime() == null ? ""
                    : userAccount.getLastAccessTime().toString());

            txtLastUpdated.setText(userAccount.getLastUpdatedTime() == null ? ""
                    : userAccount.getLastUpdatedTime().toString());
        } else {
            txtUserName.setText("");
            txtRole.setText("");
            txtLastActivity.setText("");
            txtLastUpdated.setText("");
        }

        txtNewPassword.setText("");    }

    private void setViewMode() {
        txtRole.setEnabled(false);
        txtNUID.setEnabled(false);
        txtLastActivity.setEnabled(false);
        txtLastUpdated.setEnabled(false);
        txtUserName.setEnabled(false);    }
}
