/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Business;
import Business.UserAccounts.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Business.Person.Person;
import Business.Profiles.Profile;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;

/**
 *
* @author Jianting Dong
 */
public class ManageStudents extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Business business;

    /**
     * Creates new form ManageStudents
     */
    public ManageStudents(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
    this.business = business;

    populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        btnAddStudent = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("ManageStudents");

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NUID", "Student Name", "Username", "Status", "Last Access", "Last Updated"
            }
        ));
        jScrollPane1.setViewportView(tblStudent);

        btnAddStudent.setText("Add Student");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnNext.setText("Next>>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnAddStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStudent)
                    .addComponent(btnNext)
                    .addComponent(btnBack)
                    .addComponent(btnDelete))
                .addContainerGap(182, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
String nuid = JOptionPane.showInputDialog(this, "Enter NUID:");
    if (nuid == null || nuid.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "NUID cannot be empty.");
        return;
    }

    UserAccount existing = business.getUserAccountDirectory().findUserAccount(nuid.trim());
    if (existing != null || business.getPersonDirectory().findPerson(nuid.trim()) != null) {
        JOptionPane.showMessageDialog(this, "A user with this NUID already exists.");
        return;
    }

    String name = JOptionPane.showInputDialog(this, "Enter Student Name:");
    if (name == null || name.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Student Name cannot be empty.");
        return;
    }

    String username = JOptionPane.showInputDialog(this, "Enter username:");
    if (username == null || username.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username cannot be empty.");
        return;
    }
    if (business.getUserAccountDirectory().findUserAccountByUsername(username.trim()) != null) {
        JOptionPane.showMessageDialog(this, "Username already exists.");
        return;
    }

    String password = JOptionPane.showInputDialog(this, "Enter password:");
    if (password == null || password.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Password cannot be empty.");
        return;
    }

    String email = JOptionPane.showInputDialog(this, "Enter email:");
    if (email == null || email.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Email cannot be empty.");
        return;
    }

    String department = JOptionPane.showInputDialog(this, "Enter department:");
    if (department == null || department.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Department cannot be empty.");
        return;
    }

   
    Person p = business.getPersonDirectory().newPerson(nuid.trim());
    p.setName(name.trim()); 
    p.setEmail(email.trim());
    p.setDepartment(department.trim());

    StudentProfile sp = business.getStudentDirectory().newStudentProfile(p);
    business.getUserAccountDirectory().newUserAccount(sp, username.trim(), password);

    JOptionPane.showMessageDialog(this, "Student account created successfully.");
    populateTable();
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      userProcessContainer.remove(this);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
       int selectedRowIndex = tblStudent.getSelectedRow();
    if (selectedRowIndex < 0) {
        JOptionPane.showMessageDialog(this,
                "Please select a student.",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tblStudent.getModel();
    UserAccount ua = (UserAccount) model.getValueAt(selectedRowIndex, 0);

    StudentProfile sp = (StudentProfile) ua.getAssociatedPersonProfile();

    AdminStudents panel = new AdminStudents(sp, ua, business, userProcessContainer, this);
    userProcessContainer.add("AdminStudents", panel);

    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);  
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
  int selectedRowIndex = tblStudent.getSelectedRow();
    if (selectedRowIndex < 0) {
        JOptionPane.showMessageDialog(this,
                "Please select a student to delete.",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this student account?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);

    if (confirm != JOptionPane.YES_OPTION) return;

    DefaultTableModel model = (DefaultTableModel) tblStudent.getModel();
    UserAccount ua = (UserAccount) model.getValueAt(selectedRowIndex, 0);

    business.getUserAccountDirectory().removeUserAccount(ua);

    JOptionPane.showMessageDialog(this, "Student account deleted successfully.");

    populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudent;
    // End of variables declaration//GEN-END:variables

    void populateTable() {
   DefaultTableModel model = (DefaultTableModel) tblStudent.getModel();
    model.setRowCount(0);

    for (UserAccount ua : business.getUserAccountDirectory().getUserAccountList()) {

        Profile prof = ua.getAssociatedPersonProfile();
        if (!(prof instanceof StudentProfile)) continue;

        Person p = prof.getPerson();

        Object[] row = new Object[6];
        row[0] = ua;        
        row[1] = (p == null || p.getName() == null) ? "" : p.getName();
        row[2] = ua.getUserLoginName();     
        row[3] = "Active";
        row[4] = ua.getLastAccessTime();
        row[5] = ua.getLastUpdatedTime();

        model.addRow(row);
    }
    }
    }
