/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;
import Business.Business;
import Business.Person.Person;
import Business.Profiles.Profile;
import Business.Profiles.FacultyProfile;
import Business.UserAccounts.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author stelladong
 */
public class ManageFaculty2 extends javax.swing.JPanel {
    private JPanel userProcessContainer;
private Business business;


public ManageFaculty2(JPanel userProcessContainer, Business business) {
    initComponents();
    this.userProcessContainer = userProcessContainer;
    this.business = business;

    populateTable();
}

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFaculty = new javax.swing.JTable();
        btnAddFaculty = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("ManageFaculty");

        tblFaculty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Faculty ID", "Faculty Name", "Username", "Status", "Last Access", "Last Updated"
            }
        ));
        jScrollPane1.setViewportView(tblFaculty);

        btnAddFaculty.setText("Add Faculty");
        btnAddFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFacultyActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnNext.setText("Next>>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(56, 56, 56)
                    .addComponent(btnDelete)
                    .addGap(50, 50, 50)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addContainerGap(429, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddFaculty)
                    .addComponent(btnBack)
                    .addComponent(btnNext)
                    .addComponent(btnDelete))
                .addContainerGap(231, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFacultyActionPerformed
    String fid = JOptionPane.showInputDialog(this, "Enter Faculty ID (Person ID):");
    if (fid == null || fid.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,"Faculty ID cannot be empty.","Warning",JOptionPane.WARNING_MESSAGE);
        return;
    }

    String name = JOptionPane.showInputDialog(this, "Enter Faculty Name:");
    if (name == null || name.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,"Faculty name cannot be empty.","Warning",JOptionPane.WARNING_MESSAGE);
        return;
    }

    String email = JOptionPane.showInputDialog(this, "Enter Email:");
    if (email == null || email.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,"Email cannot be empty.","Warning",JOptionPane.WARNING_MESSAGE);
        return;
    }

    String username = JOptionPane.showInputDialog(this, "Enter username:");
    if (username == null || username.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,"Username cannot be empty.","Warning",JOptionPane.WARNING_MESSAGE);
        return;
    }

    String password = JOptionPane.showInputDialog(this, "Enter password:");
    if (password == null || password.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,"Password cannot be empty.","Warning",JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (business.getPersonDirectory().findPerson(fid.trim()) != null) {
        JOptionPane.showMessageDialog(this, "Faculty ID already exists.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (business.getUserAccountDirectory().findUserAccountByUsername(username.trim()) != null) {
        JOptionPane.showMessageDialog(this, "Username already exists.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    //Ren p = business.getPersonDirectory().newPerson(fid.trim());
   // p.setName(name.trim());
   // p.setEmail(email.trim());

    //FacultyProfile fp = business.getFacultyDirectory().newFacultyProfile(p);
   // business.getUserAccountDirectory().newUserAccount(fp, username.trim(), password);

    JOptionPane.showMessageDialog(this, "Faculty account created successfully.");
    populateTable();
     
    }//GEN-LAST:event_btnAddFacultyActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
userProcessContainer.remove(this);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.previous(userProcessContainer);    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
    

    }//GEN-LAST:event_btnNextActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
 int selectedRowIndex = tblFaculty.getSelectedRow();
    if (selectedRowIndex < 0) {
        JOptionPane.showMessageDialog(this,
                "Please select a faculty to delete.",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this faculty account?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tblFaculty.getModel();
    String username = (String) model.getValueAt(selectedRowIndex, 2);
    
    UserAccount ua = business.getUserAccountDirectory().findUserAccountByUsername(username);
    
    if (ua == null) {
        JOptionPane.showMessageDialog(this, "User account not found.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    business.getUserAccountDirectory().removeUserAccount(ua);

    JOptionPane.showMessageDialog(this,
            "Faculty account deleted successfully.",
            "Deleted",
            JOptionPane.INFORMATION_MESSAGE);

    populateTable();


    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFaculty;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFaculty;
    // End of variables declaration//GEN-END:variables

    void populateTable() {
     DefaultTableModel model = (DefaultTableModel) tblFaculty.getModel();
    model.setRowCount(0);

    for (UserAccount ua : business.getUserAccountDirectory().getUserAccountList()) {

        if (ua.getRole() != null && ua.getRole().toLowerCase().contains("faculty")) {

            Object[] row = new Object[6];

            Profile prof = ua.getAssociatedPersonProfile();
           Person p =null; //(prof == null) ? null : prof.getPerson();

            String facultyId = "";
            String facultyName = "";
            if (p != null) {
                facultyId = p.getPersonId();
                facultyName = p.getName();
                if (facultyName == null || facultyName.trim().isEmpty()) {
                    facultyName = p.getPersonId();
                }
            }
            
            row[0] = facultyId;
            row[1] = facultyName;
            row[2] = ua.getUserLoginName();
            row[3] = "Active";
            row[4] = ua.getLastAccessTime() != null ? ua.getLastAccessTime() : "N/A";
            row[5] = ua.getLastUpdatedTime() != null ? ua.getLastUpdatedTime() : "N/A";

           // model.addRow(row);
        
       }
     }
   }
}
