/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.FacultyRoleWorkResp02;

import Business.Business;
import Business.Profiles.FacultyProfile;
import Business.Profiles.StudentProfile;
import Business.Profiles.StudentDirectory;
import Business.Academic.Enrollment;
import Business.Academic.EnrollmentDirectory;
import Business.Person.Person;

import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jiachuan Li
 */
public class ManageStudentsProfilesJPanel extends javax.swing.JPanel {

    Business business;
    FacultyProfile faculty;
    JPanel CardSequencePanel;

    public ManageStudentsProfilesJPanel(Business b, FacultyProfile fp, JPanel clp) {
        business = b;
        faculty = fp;
        CardSequencePanel = clp;
        initComponents();
        
        loadStudents();
    }

    public ManageStudentsProfilesJPanel() {
        initComponents();
    }

    private void loadStudents() {
        StudentDirectory sd = business.getStudentDirectory();
        ArrayList<StudentProfile> students = sd.getStudentList();
        
        DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
        model.setRowCount(0);
        
        for (StudentProfile sp : students) {
            if (sp.getPerson() != null) {
                model.addRow(new Object[]{
                    sp.getPerson().getPersonId(),
                    sp.getPerson().getPersonId(),
                    sp.getHobbies() != null ? sp.getHobbies() : "N/A",
                    sp.getInterests() != null ? sp.getInterests() : "N/A",
                    getAcademicProgress(sp.getPerson().getPersonId())
                });
            }
        }
    }

    private String getAcademicProgress(String studentId) {
        EnrollmentDirectory ed = business.getEnrollmentDirectory();
        ArrayList<Enrollment> enrollments = ed.getEnrollmentsForStudent(studentId);
        
        if (enrollments.isEmpty()) {
            return "No enrollments";
        }
        
        double total = 0;
        int count = 0;
        for (Enrollment e : enrollments) {
            if (e.getGradePoint() != null) {
                total += e.getGradePoint();
                count++;
            }
        }
        
        if (count == 0) {
            return "In Progress";
        }
        
        double avg = total / count;
        return String.format("GPA: %.2f", avg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Hobbies", "Interests", "Academic Progress"
            }
        ));
        jScrollPane1.setViewportView(tblCourses);

        jButton1.setText("Back");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(54, 54, 54))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardSequencePanel.removeAll();
        UserInterface.WorkAreas.FacultyRole.FacultyWorkAreaJPanel panel = 
            new UserInterface.WorkAreas.FacultyRole.FacultyWorkAreaJPanel(business, CardSequencePanel, null);
        CardSequencePanel.add("FacultyWorkArea", panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourses;
    // End of variables declaration//GEN-END:variables
}
