/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.FacultyRoleWorkResp02;

import Business.Business;
import Business.Profiles.FacultyProfile;
import Business.Academic.CourseInfo;
import Business.Academic.CourseDirectory;
import Business.Academic.Enrollment;
import Business.Academic.EnrollmentDirectory;
import Business.Profiles.StudentProfile;
import Business.Profiles.StudentDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jiachuan Li
 */
public class PerformanceReportsJPanel extends javax.swing.JPanel {

    Business business;
    FacultyProfile faculty;
    JPanel CardSequencePanel;

    public PerformanceReportsJPanel(Business b, FacultyProfile fp, JPanel clp) {
        business = b;
        faculty = fp;
        CardSequencePanel = clp;
        initComponents();
        
        loadCourses();
    }

    public PerformanceReportsJPanel() {
        initComponents();
    }

    private void loadCourses() {
        if (faculty == null || faculty.getPerson() == null) {
            return;
        }
        
        CourseDirectory cd = business.getCourseDirectory();
        ArrayList<CourseInfo> courses = cd.getCoursesForFaculty(faculty.getPerson().getPersonId());
        
        jComboBox1.removeAllItems();
        
        for (CourseInfo course : courses) {
            jComboBox1.addItem(course.getCourseId() + " - " + course.getCourseName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Grade", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblCourses);

        jLabel1.setText("Select Course:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CS101 - Introduction to Programming", "CS201 - Data Structures & Algorithms", "CS301 - Database Management Systems", "CS401 - Software Engineering" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jButton1.setText("Generate Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 if (CardSequencePanel == null) {
        return;  
    }

    CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
    CardSequencePanel.remove(this);              
    layout.previous(CardSequencePanel); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String selected = (String) jComboBox1.getSelectedItem();
        
        if (selected == null || selected.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a course", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String courseId = selected.split(" - ")[0];
        
        EnrollmentDirectory ed = business.getEnrollmentDirectory();
        ArrayList<Enrollment> enrollments = ed.getEnrollmentsForStudent("");
        
        DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
        model.setRowCount(0);
        
        StudentDirectory sd = business.getStudentDirectory();
        ArrayList<StudentProfile> allStudents = sd.getStudentList();
        
        for (StudentProfile sp : allStudents) {
            if (sp.getPerson() != null) {
                String studentId = sp.getPerson().getPersonId();
                ArrayList<Enrollment> studentEnrollments = ed.getEnrollmentsForStudent(studentId);
                
                for (Enrollment e : studentEnrollments) {
                    if (e.getCourseId().equals(courseId) && e.getGradePoint() != null) {
                        String status = e.getGradePoint() >= 1.0 ? "Pass" : "Fail";
                        
                        model.addRow(new Object[]{
                            studentId,
                            studentId,
                            String.format("%.2f", e.getGradePoint()),
                            status
                        });
                    }
                }
            }
        }
        
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No grades found for this course", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourses;
    // End of variables declaration//GEN-END:variables
}
